name: "🐛 Bug Report"
description: Report a bug to help us improve
title: "[BUG] "
labels: ["Type: Bug"]
assignees:
  - smcnab1
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of the problem.
      placeholder: "The app crashes when I click X..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the bug? List each step.
      placeholder: |
        1. Go to...
        2. Click on...
        3. Scroll down to...
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: "It should show Y instead of crashing."
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or videos
      description: Add supporting visuals if available.

  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, browser/device, version details
      placeholder: "e.g. macOS 14 / Chrome 118"

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Anything else that might help us understand the issue.
