name: "⚙️ Feature Request"
description: Suggest an idea to improve the project
title: "[FR] "
labels: ["Type: Feature"]
assignees:
  - smcnab1
body:
  - type: textarea
    id: problem
    attributes:
      label: Related problem
      description: Is your feature request related to a problem? If so, describe it.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: A clear and concise description of what you want to happen.
      placeholder: "Add support for X to improve Y."

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What other solutions or features have you thought about?
      placeholder: "I also considered using Z..."

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Anything else we should know?
      placeholder: "Screenshots, references, or examples..."

  - type: checkboxes
    id: tasks
    attributes:
      label: Tasks
      description: Steps or subtasks that need to be done for this feature.
      options:
        - label: Task 1
        - label: Task 2
        - label: Task 3
