name: "🚀 Enhancement Request"
description: Suggest an enhancement to improve an existing feature
title: "[ENH] "
labels: ["Type: Enhancement"]
assignees:
  - smcnab1
body:
  - type: textarea
    id: problem
    attributes:
      label: Related problem
      description: Is your enhancement request related to a problem? If so, describe it.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: A clear and concise description of the improvement you’d like to see.
      placeholder: "Improve X to make Y easier."

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What other solutions or approaches have you thought about?
      placeholder: "Alternatively, Z could be improved..."

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Anything else we should know?
      placeholder: "Screenshots, references, or examples..."
