name: "⚠️ Security Report"
description: Report a security issue responsibly
title: "[SR] "
labels: ["P0 – Critical", "Type: Bug", "Type: Security"]
assignees:
  - smcnab1
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **Important**  
        If your report contains sensitive or exploitable details, **do not post them here**.  
        Instead, please email: **sammcnab.email@gmail.com**  
        Only share minimal details publicly.

  - type: textarea
    id: description
    attributes:
      label: Describe the security issue
      description: A clear and concise description of the vulnerability.
      placeholder: "e.g., X endpoint exposes sensitive data..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. Go to...
        2. Perform...
        3. Observe...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: What should happen if the issue didn’t exist?
      placeholder: "The system should reject unauthorised access."
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, device, browser, and version details.
      placeholder: "macOS 14, Chrome 118, iPhone 14 Pro..."

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Any further context, screenshots, or references.
