blank_issues_enabled: false
contact_links:
  - name: 📧 Email the developer
    url: mailto:sam@sammcnab.co.uk
    about: For important business or personal contact only. Do not use for issues or feature requests.
